import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutClient from "@/components/LayoutClient";
import { MyAppProvider } from "@/context/MyAppContext";
import Preloader from "@/components/Custom/Preloader";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Street Buddy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-[#F5F6F8] overflow-y-auto w-full overflow-x-hidden">
          {/* <Header /> */}
          {/* <Preloader /> */}
          <AuthProvider>
            <MyAppProvider>
              {/* <LayoutClient> */}

              {children}
              {/* </LayoutClient> */}
            </MyAppProvider>
          </AuthProvider>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
